language: python
python:
  - "3.6"
install:
  - pip install -r test_requirements.txt
script:
  - python -m pytest --cov=utils --cov=python --cov=converters test 
after_success:
  - coveralls
notifications:
  email: false
